### ISSUE TITLE
Check changes necessary for v8

### ISSUE THREAD

**Issue by ofpiyush** [verloop/twirpy#31]
https://github.com/twitchtv/twirp/pull/304

**Comment by marioizquierdo** [comment]
Thanks for tracking this major version release. However, I think that is a Golang release only, there are no changes on the protocol or interactions outside of Golang protobuf updates.

**Comment by ofpiyush** [comment]
@marioizquierdo thank you for that!

I suspected as much, but wanted to be sure.

You've just saved me a day of going through the PR 😅
